### ISSUE TITLE
コメント元自動選択について

### ISSUE THREAD

**Issue by noriokun4649** [silane/TVTComment#1]
開発ありがとうございます。忙しいかと思いますが気づいた事があったので書かせていただきました。

問題1
----

メインウィンドウのコメント元の自動選択にチェックを入れた上で
設定->その他の設定->一般より、コメント元自動選択の放送中番組視聴時に「新ニコニコ実況」にチェックを入れると視聴時に、新ニコニコ実況のコメントが二重で選択・追加される。

問題2
----

メインウィンドウのコメント元の「自動選択する」にチェックを入れた状態で起動された場合、「自動選択する」のチェックボックスを外しても「追加↑」「削除↓」のボタンのisEnableがfalseのままに固定される。

再現性
----
あり

バージョン
----
TVTComment : v1.6.1
TvTest : v0.10.0　devブランチの最新コミット分を自ビルド

**Comment by silane** [comment]
報告ありがとうございます。こちらでも両方とも問題を確認しました。

問題2については解決できました。バージョン1.6.2を使ってください。
問題1はそもそもその辺の処理が全体的におかしいことに気づいたので時間がかかるかもしれません。致命的なバグでもないのでしばらくお待ちください。

**Comment by noriokun4649** [comment]
分かりました。ありがとうございます。

**Comment by silane** [comment]
#2  および d3846fa0 で修正
